on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: imjasonh/setup-crane@v0.4
        with:
          version: v0.20.5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up GitHub Actions bot user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Prepare (checkouts & patches)
        run: make checkouts patches

      - name: Kernel
        run: make kernel

      - name: Overlay
        run: make overlay

      - name: Installer
        run: make installer

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: make release

      - uses: actions/upload-artifact@v4
        with:
          name: metal-arm64.raw.zst
          path: ./checkouts/talos/_out/metal-arm64.raw.zst
          compression-level: 0
